name: Tests
on:
  pull_request:
    branches:
      - main

  workflow_call: # Reused in build-publish

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Cache Poetry Virtual Environment
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies With Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Remove Cache Files
        run: |
          find . -type f -name "*.py[co]" -delete
          find . -type d -name "__pycache__" -delete

      - name: Run Tests
        run: poetry run pytest
